# Generated by Django 2.1.4 on 2018-12-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DrugStore',
            fields=[
                ('idDrug', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('expiredDate', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Email', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=20)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='idR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='patient',
            name='idP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='manager',
            name='idM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='idD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='idA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
    ]
