# Generated by Django 2.1.4 on 2018-12-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('role', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('postalCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='idR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='patient',
            name='idP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='idN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='manager',
            name='idM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='idD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
        migrations.AddField(
            model_name='accountant',
            name='idA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalsite.User'),
        ),
    ]
